/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import java.sql.Connection;
import java.util.List;
import model.Project;
import util.ConnectionFactory;

public class App {
    public static void main(String[] args) {         
        //ProjectController projectController = new ProjectController();
        
        //Project project = new Project();
        //project.setName("Projeto teste 2");
        //project.setDescription("description");
        //projectController.save(project);
        
        ProjectController projectController = new ProjectController();
        
        Project project = new Project();
        project.setId(2);
        project.setName("Novo nome do projeto");
        project.setDescription("description");
        
        projectController.update(project);
        
        List<Project> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
        
        projectController.removeById(2);
    }
}
